
// This file has been generated by the GUI designer. Do not modify.
namespace UI
{
	public partial class ToolBarView
	{
		private global::Gtk.UIManager UIManager;
		private global::Gtk.RadioAction tool2;
		private global::Gtk.RadioAction tool1;
		private global::Gtk.RadioAction tool11;
		private global::Gtk.RadioAction tool21;
		private global::Gtk.RadioAction tool3;
		private global::Gtk.RadioAction tool4;
		private global::Gtk.Toolbar toolbar4;
		
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget UI.ToolBarView
			Stetic.BinContainer w1 = global::Stetic.BinContainer.Attach (this);
			this.UIManager = new global::Gtk.UIManager ();
			global::Gtk.ActionGroup w2 = new global::Gtk.ActionGroup ("Default");
			this.tool2 = new global::Gtk.RadioAction ("tool2", global::Mono.Unix.Catalog.GetString ("tool2"), null, "gtk-yes", 0);
			this.tool2.Group = new global::GLib.SList (global::System.IntPtr.Zero);
			this.tool2.ShortLabel = global::Mono.Unix.Catalog.GetString ("tool2");
			w2.Add (this.tool2, null);
			this.tool1 = new global::Gtk.RadioAction ("tool1", global::Mono.Unix.Catalog.GetString ("tool1"), null, "gtk-cancel", 0);
			this.tool1.Group = this.tool2.Group;
			this.tool1.ShortLabel = global::Mono.Unix.Catalog.GetString ("tool1");
			w2.Add (this.tool1, null);
			this.tool11 = new global::Gtk.RadioAction ("tool11", null, null, "gtk-yes", 0);
			this.tool11.Group = this.tool2.Group;
			w2.Add (this.tool11, null);
			this.tool21 = new global::Gtk.RadioAction ("tool21", null, null, "gtk-cancel", 0);
			this.tool21.Group = this.tool2.Group;
			w2.Add (this.tool21, null);
			this.tool3 = new global::Gtk.RadioAction ("tool3", null, null, "gtk-refresh", 0);
			this.tool3.Group = this.tool2.Group;
			w2.Add (this.tool3, null);
			this.tool4 = new global::Gtk.RadioAction ("tool4", null, null, "gtk-redo", 0);
			this.tool4.Group = this.tool2.Group;
			w2.Add (this.tool4, null);
			this.UIManager.InsertActionGroup (w2, 0);
			this.Name = "UI.ToolBarView";
			// Container child UI.ToolBarView.Gtk.Container+ContainerChild
			this.UIManager.AddUiFromString ("<ui><toolbar name=\'toolbar4\'><toolitem name=\'tool11\' action=\'tool11\'/><toolitem n" +
				"ame=\'tool21\' action=\'tool21\'/><toolitem name=\'tool3\' action=\'tool3\'/><toolitem n" +
				"ame=\'tool4\' action=\'tool4\'/></toolbar></ui>");
			this.toolbar4 = ((global::Gtk.Toolbar)(this.UIManager.GetWidget ("/toolbar4")));
			this.toolbar4.Name = "toolbar4";
			this.toolbar4.ShowArrow = false;
			this.Add (this.toolbar4);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			w1.SetUiManager (UIManager);
			this.Hide ();
		}
	}
}
