
// This file has been generated by the GUI designer. Do not modify.
namespace UI
{
	public partial class ToolBarView
	{
		private global::Gtk.UIManager UIManager;
		private global::Gtk.RadioAction tool2;
		private global::Gtk.RadioAction tool1;
		private global::Gtk.RadioAction connectedTool;
		private global::Gtk.RadioAction unconnectedTool;
		private global::Gtk.RadioAction momentTool;
		private global::Gtk.RadioAction forceTool;
		private global::Gtk.RadioAction selectionTool;
		private global::Gtk.RadioAction jointTool;
		private global::Gtk.Toolbar toolbar4;
		
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget UI.ToolBarView
			Stetic.BinContainer w1 = global::Stetic.BinContainer.Attach (this);
			this.UIManager = new global::Gtk.UIManager ();
			global::Gtk.ActionGroup w2 = new global::Gtk.ActionGroup ("Default");
			this.tool2 = new global::Gtk.RadioAction ("tool2", global::Mono.Unix.Catalog.GetString ("tool2"), null, "gtk-yes", 0);
			this.tool2.Group = new global::GLib.SList (global::System.IntPtr.Zero);
			this.tool2.ShortLabel = global::Mono.Unix.Catalog.GetString ("tool2");
			w2.Add (this.tool2, null);
			this.tool1 = new global::Gtk.RadioAction ("tool1", global::Mono.Unix.Catalog.GetString ("tool1"), null, "gtk-cancel", 0);
			this.tool1.Group = this.tool2.Group;
			this.tool1.ShortLabel = global::Mono.Unix.Catalog.GetString ("tool1");
			w2.Add (this.tool1, null);
			this.connectedTool = new global::Gtk.RadioAction ("connectedTool", global::Mono.Unix.Catalog.GetString ("_Connected"), null, "gtk-yes", 0);
			this.connectedTool.Group = this.tool1.Group;
			this.connectedTool.ShortLabel = global::Mono.Unix.Catalog.GetString ("_Connected");
			w2.Add (this.connectedTool, null);
			this.unconnectedTool = new global::Gtk.RadioAction ("unconnectedTool", global::Mono.Unix.Catalog.GetString ("_Unconencted"), null, "gtk-cancel", 0);
			this.unconnectedTool.Group = this.connectedTool.Group;
			this.unconnectedTool.ShortLabel = global::Mono.Unix.Catalog.GetString ("_Unconencted");
			w2.Add (this.unconnectedTool, null);
			this.momentTool = new global::Gtk.RadioAction ("momentTool", global::Mono.Unix.Catalog.GetString ("_Moment"), null, "gtk-refresh", 0);
			this.momentTool.Group = this.unconnectedTool.Group;
			this.momentTool.ShortLabel = global::Mono.Unix.Catalog.GetString ("_Moment");
			w2.Add (this.momentTool, null);
			this.forceTool = new global::Gtk.RadioAction ("forceTool", global::Mono.Unix.Catalog.GetString ("_Force"), null, "gtk-redo", 0);
			this.forceTool.Group = this.unconnectedTool.Group;
			this.forceTool.ShortLabel = global::Mono.Unix.Catalog.GetString ("_Force");
			w2.Add (this.forceTool, null);
			this.selectionTool = new global::Gtk.RadioAction ("selectionTool", global::Mono.Unix.Catalog.GetString ("_Selection"), null, "gtk-add", 0);
			this.selectionTool.Group = this.unconnectedTool.Group;
			this.selectionTool.ShortLabel = global::Mono.Unix.Catalog.GetString ("_Selection");
			w2.Add (this.selectionTool, null);
			this.jointTool = new global::Gtk.RadioAction ("jointTool", null, null, "gtk-home", 0);
			this.jointTool.Group = this.unconnectedTool.Group;
			w2.Add (this.jointTool, null);
			this.UIManager.InsertActionGroup (w2, 0);
			this.Name = "UI.ToolBarView";
			// Container child UI.ToolBarView.Gtk.Container+ContainerChild
			this.UIManager.AddUiFromString ("<ui><toolbar name='toolbar4'><toolitem name='connectedTool' action='connectedTool'/><toolitem name='unconnectedTool' action='unconnectedTool'/><toolitem name='momentTool' action='momentTool'/><toolitem name='forceTool' action='forceTool'/><toolitem name='selectionTool' action='selectionTool'/><toolitem name='jointTool' action='jointTool'/></toolbar></ui>");
			this.toolbar4 = ((global::Gtk.Toolbar)(this.UIManager.GetWidget ("/toolbar4")));
			this.toolbar4.Name = "toolbar4";
			this.toolbar4.ShowArrow = false;
			this.Add (this.toolbar4);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			w1.SetUiManager (UIManager);
			this.Hide ();
		}
	}
}
